### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by illuminatedwax** [crmarsh/discord-linux-bugs#2]
On XUbuntu
Running the executable on the command line (I tried both the .tar.gz and .deb 0.0.2 packages), I get the following crash immediately after running:

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/usr/share/discord-canary/resources/app.asar/app/SplashWindow.js:66:27)
    at /usr/share/discord-canary/resources/app.asar/app/index.js:611:22
    at Socket.<anonymous> (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:59:7)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

My md5sums:

> 
> 6b3819b3c83cc9b92b67461359cb7315  discord-canary-0.0.2.tar.gz
> d3cffec6779075f2fff355f314159bd0  ../Downloads/discord-canary-0.0.2.deb
> 

My uname -a:

> 
Linux trashboat 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

My lsb_release -a:

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 15.10
> Release:	15.10
> Codename:	wily

**Comment by crmarsh** [comment]
Fix coming in next version

**Comment by crmarsh** [comment]
Fixed in 0.0.3

**Comment by Limeth** [comment]
On elementaryOS Freya, still getting this issue:
```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at SplashWindow.focus (/usr/share/discord-canary/resources/app.asar/app/SplashWindow.js:66:27)
    at /usr/share/discord-canary/resources/app.asar/app/index.js:611:22
    at Socket.<anonymous> (/usr/share/discord-canary/resources/app.asar/app/singleInstance.js:59:7)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

md5sum
`1a56b6ae43c2e31b80f9995a8b6402c9  discord-canary-0.0.6.deb`

uname -a
`Linux LimeBox 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

lsb_release -a
```
No LSB modules are available.
Distributor ID: elementary OS
Description:    elementary OS Freya
Release:        0.3.2
Codename:       freya
```
